[build]
command = "npm run build"
publish="/build'
base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"