// <auto-generated />
using ClothingWebsite.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingWebsite.Server.Migrations
{
    [DbContext(typeof(QuanAoContext))]
    [Migration("20250224152641_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingWebsite.Server.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSanP__730A5759C110543F");

                    b.HasIndex(new[] { "Loai" }, "UQ__LoaiSanP__4E48BB75231FA042")
                        .IsUnique();

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.MauSanPham", b =>
                {
                    b.Property<int>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMau"));

                    b.Property<string>("Mau")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("MaMau")
                        .HasName("PK__MauSanPh__3A5BBB7D8523C8FE");

                    b.HasIndex(new[] { "Mau" }, "UQ__MauSanPh__C7977BC2A4AF3D99")
                        .IsUnique();

                    b.ToTable("MauSanPham", (string)null);
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442DA12C8AC9");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaMau");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.SanPhamKhachHang", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaTaiKhoan", "MaSanPham")
                        .HasName("PK__SanPhamK__62D0116B4FE28E24");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SanPhamKhachHang", (string)null);
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuyenTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TaiKhoan__AD7C652946046DC5");

                    b.HasIndex(new[] { "Username" }, "UQ__TaiKhoan__536C85E46D7C7386")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.SanPham", b =>
                {
                    b.HasOne("ClothingWebsite.Server.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__MaLoai__4222D4EF");

                    b.HasOne("ClothingWebsite.Server.Models.MauSanPham", "MaMauNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__MaMau__4316F928");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MaMauNavigation");
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.SanPhamKhachHang", b =>
                {
                    b.HasOne("ClothingWebsite.Server.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("SanPhamKhachHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamKh__MaSan__47DBAE45");

                    b.HasOne("ClothingWebsite.Server.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("SanPhamKhachHangs")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamKh__MaTai__46E78A0C");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.MauSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamKhachHangs");
                });

            modelBuilder.Entity("ClothingWebsite.Server.Models.TaiKhoan", b =>
                {
                    b.Navigation("SanPhamKhachHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
